# Server settings
server:
  port: 8080
  servlet:
    context-path: /file

#log
logging:
  level:
     ROOT: info
  file: file.log

spring:
    servlet:
        multipart:
          max-request-size: 100MB
          max-file-size: 100MB
    redis:
      host: 127.0.0.1
      port: 6379
      password: test
      database: 15
      timeout: 3000
      jedis:
        pool:
          max-active: 600
          max-idle: 30
          max-wait: 10

remote:
    file:
       url: http://localhost:8081/mongodbstu/single/fileupload.do

file:
   engine:
      local:
         path: /home/scd/upload
         enable: true
      sftp:
         host: 192.168.1.101
         port: 22
         username: test
         password: testT2018
         path: /sftpupload
         enable: false
      ftp:
         host: 192.168.1.101
         port: 21
         username: test
         password: testT2018
         path: /ftpupload
         enable: false
      fdfs:
         config: fdfs/fdfsclient.conf
         group: group1
         enable: false
      mongo:
         host: 127.0.0.1
         port: 27017
         database: mongotest
         username: chengdu
         password: test
         connectionsPerHost: 8
         minConnectionsPerHost: 3
         threadsAllowedToBlockForConnectionMultiplier: 4
         connectTimeout: 3000
         maxWaitTime: 4000
         socketTimeout: 4000
         enable: true

pool:
  file:
     corePoolSize: 28
     maximumPoolSize: 66
     keepAliveTime: 60
     timeUnit: SECONDS
     blockingQueue: 2000
  sftp:
     maxTotal: 100
     maxIdle: 28
     maxWait: 3000
     testWhileIdle: true
     timeBetweenEvictionRunsMillis: 600000
  ftp:
     maxTotal: 100
     maxIdle: 28
     maxWait: 3000
     testWhileIdle: true
     timeBetweenEvictionRunsMillis: 60000

temp:
  mergebreakpath: /temp/breakmerge